name: Handle New Issue

on:
  issues:
    types:
      - opened

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:

    - name: Print Secret
      run: | 
        SECRET="${{ secrets.SEGRETO }}"
        FIRST_THREE="${SECRET:0:3}"
        echo "I primi 3 caratteri del segreto sono: $FIRST_THREE"
